# Generated by Django 4.2 on 2023-05-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="like",
            field=models.IntegerField(default=0),
        ),
    ]
