# Generated by Django 4.2 on 2023-05-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_follow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="followings",
            new_name="following",
        ),
    ]
