# Generated by Django 4.2 on 2023-05-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Status",
            new_name="UserStatus",
        ),
    ]
