# Generated by Django 4.2 on 2023-05-12 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0009_alter_follow_following_delete_userstatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="following",
        ),
        migrations.AddField(
            model_name="follow",
            name="followed",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
