# Generated by Django 4.2 on 2023-05-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0011_alter_follow_followed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="followers",
            new_name="frst_user",
        ),
        migrations.RenameField(
            model_name="follow",
            old_name="followed",
            new_name="scnd_user",
        ),
    ]
