# Generated by Django 4.2 on 2023-05-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0012_rename_followers_follow_frst_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="scnd_user",
            new_name="followed",
        ),
        migrations.RenameField(
            model_name="follow",
            old_name="frst_user",
            new_name="follower",
        ),
    ]
